const sections1 = [
  {
    id: '1.1',
    dicr: 'Kết quả học tập (Xuất sắc: +15đ, Giỏi: +12đ, Khá: +10đ, TB Khá: +8đ, Trung bình: +5đ) ',
    note: '',
    score: '',
    inputType: 'number',
  },
  {
    id: '1.2',
    dicr: 'Xếp loại học tập tăng ….bậc, từ…….lên…....(+3đ, +5đ) ',
    note: '(Tăng 1 bậc +3đ, tăng 2 bậc +5đ)',
    score: '',
    inputType: 'number',
  },
  {
    id: '1.3',
    dicr: 'Có tham gia nghiên cứu khoa học ',
    note: '(Có minh chứng kèm theo)',
    score: 5,
    inputType: 'number',
  },
  {
    id: '1.4',
    dicr: 'Có tham gia các câu lạc bộ học thuật (Anh văn, Tin học…) ',
    note: '(Có minh chứng kèm theo)',
    score: 5,
    inputType: 'number',
  },
  {
    id: '1.5',
    dicr: 'Có tham gia các câu lạc bộ học thuật (Anh văn, Tin học…) ',
    note: '(Có minh chứng kèm theo)',
    score: 5,
    inputType: 'number',
  },
  {
    id: '1.6',
    dicr: 'Nghỉ học không phép  (– 01điểm/01 buổi) ',
    note: '',
    score: -1,
    inputType: 'number',
  },
  {
    id: '1.7',
    dicr: 'Nghỉ học có phép (– 01điểm/05 buổi) ',
    note: '',
    score: -1,
    inputType: 'number',
  },
  {
    id: '1.8',
    dicr: ' Có thái độ học tập chưa tốt (Giảng viên mời ra khỏi lớp, ……..) mỗi lần vi phạm (- 5đ/lần)',
    note: '',
    score: -5,
    inputType: 'number',
  },
];
const sections2 = [
  {
    id: '2.1',
    dicr: 'Ý thức chấp hành các văn bản của ngành, cơ quan chỉ đạo cấp trên (Đăng ký nội trú, ngoại trú, khám sức khỏe, Phiếu QLSV, hồ sơ nhập học, đóng học phí, tham gia BHYT)',
    note: '(Không thực hiện một nội dung không được cộng điểm)',
    score: '10',
    inputType: 'number',
  },
  {
    id: '2.2',
    dicr: 'Tham gia các buổi sinh hoạt của Lớp (mỗi lần được +0.5đ/lần sinh hoạt)',
    note: '(Mỗi học kỳ cộng không quá 5đ)',
    score: '',
    inputType: 'number',
  },
  {
    id: '2.3',
    dicr: '- Sinh hoạt đầu khoá (XS: +5đ, Giỏi: +4đ, Khá: +3đ) (Áp dụng cho SV khoá mới nhập học)   -  Tham gia SH đầu năm, cuối khoá (+3đ) (Có minh chứng kèm theo)',
    note: '(Có minh chứng kèm theo)',
    score: '',
    inputType: 'number',
  },
  {
    id: '2.4',
    dicr: 'Đánh giá giảng dạy của giảng viên +(1đ - 5đ) ',
    note: '(Có tham gia từ: 10-29%: +1đ; 33-49%: +2đ; 50-69%:+3đ; 70-85%: +4đ; 86-100%: + 5đ)',
    score: '',
    inputType: 'number',
  },
  {
    id: '2.5',
    dicr: ' Đánh giá giáo viên chủ nhiệm',
    note: '',
    score: '5',
    inputType: 'number',
  },
  {
    id: '2.6',
    dicr: 'Sinh viên nghiên cứu và học tập tại Thư viện (+0.5 đ/lần)',
    note: '(Mỗi học kỳ cộng không quá 5đ)',
    score: '',
    inputType: 'number',
  },
  {
    id: '2.7',
    dicr: 'Vi phạm các nội quy, quy chế của trường, của Ký túc xá, vi phạm quy chế thi: Vi phạm bị lập biên bản: (- 5đ/lần)',
    note: '',
    score: '',
    inputType: 'number',
  },
];
export { sections1, sections2 };
